import Footer from "@/components/common/Footer";
import Navbar from "@/components/common/navbar";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
